[tool]
[tool.poetry]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.version }}"
description = "Top-level package for {{ cookiecutter.project_name }}."
authors = ["{{ cookiecutter.full_name }} <{{ cookiecutter.email }}>"]
readme = "README.rst"
{$ if cookiecutter.open_source_license != 'Not open source' -%}
license =  "{{ cookiecutter.open_source_license }}
{%- endif -%}"

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
bumpversion = "*"
coverage = "*"
flake8 = "*"
invoke = "*"
isort = "*"
pylint = "*"
{% if cookiecutter.use_pytest == 'y' -%}
pytest = "*"{% endif %}
sphinx = "*"
tox = "*"
twine = "*"
wheel = "*"
yapf = "*"
